import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tidal Collage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-900 text-gray-100 p-8 flex items-start justify-center">
          <div className="w-full max-w-4xl">
            <header className="text-center mb-6">
              <h1 className="text-4xl font-extrabold tracking-tight mb-2">
                <Link href="/">
                  Tidal Collage
                </Link>
              </h1>
              <p className="text-gray-300">Create a tiled collage of your playlist covers — pick a resolution and export a PNG.</p>
            </header>
    
            <div className="bg-linear-to-r from-gray-800 to-gray-900/80 p-6 rounded-lg shadow-xl">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
